[package]
name = "sporkbot_rs"
version = "0.1.0"
authors = ["snipey"]
edition = "2018"


[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
chrono = "0.4"
dissolve = "0.2"
dotenv = "0.15"
indexmap = "1.3"
lazy_static = "1.4"
libmath = "0.2"
log = "0.4"
time = "0.1"
rand = "0.7"
regex = "1"
reqwest = { version = "0.10", features = ["blocking", "json"] }
rust-embed = "5.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sys-info = "0.5"
sysinfo = "0.9"
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "current" } 

[dependencies.fern]
version = "0.5"
features = ["colored"]

[dependencies.diesel]
version = "1.0.0"
features = ["postgres", "chrono", "r2d2"]

[dependencies.urbandictionary]
git = "https://github.com/youssefhabri/urbandictionary.rs"